[theme]
base = "light"
primaryColor = "#FF4821"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F8F8FA"
textColor = "#000000"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
